# Generated by Django 5.0.6 on 2024-05-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
