# Generated by Django 5.0.4 on 2024-05-31 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggie', '0004_recipe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
