# Generated by Django 5.0.6 on 2024-05-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('Image', models.ImageField(upload_to='')),
                ('File', models.FileField(upload_to='')),
            ],
        ),
    ]
