# Generated by Django 5.0.6 on 2024-05-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
