# Generated by Django 5.0.6 on 2024-05-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='name',
            new_name='car_name',
        ),
        migrations.AlterField(
            model_name='car',
            name='speed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='Address',
            field=models.TextField(default='unknown car'),
            preserve_default=False,
        ),
    ]
